### ISSUE TITLE
Accounts -> Transactions Page UI

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#34]
![Screen Shot 2020-07-13 at 8 20 10 PM](https://user-images.githubusercontent.com/5943963/87379965-4f7a0200-c546-11ea-9313-242bf4dbd2ee.png)

figma link: https://www.figma.com/file/M4wHv7B4JNig3bH2cywI9u/Accounts?node-id=46%3A280

- When you click the `TRANSACTIONS` tab, it should take you to the transaction page.
- Make the table with fake data.
- When you click the triangle button on a row, it should expand to show all the rows for the hash ids. (there should be four rows total, with 16 characters in each row)

**Comment by sabinbajracharya** [comment]
1. Currently the PageTable component is used to display the content and has `hardcoded table header and row data`. Do we make the `PageTable component dynamic` by passing the header and row data based on tab (Overview, Transactions, etc) selection or create `separate PageTable component` for each tabs?

2. The transactions tab is in Account, Bank and Validator container. Should transactions tab work in all these container?

3. When pressing the triangle button on a row,  did you meant that instead of the truncated text the full text needs to be shown?

**Comment by angle943** [comment]
1. Ah good call. As part of this ticket, lets make the `PageTable` a reusable component. This way, no need to create a separate `PageTable` component.

2) No, just the Accounts table for now. The links to `Bank` and `Validators` dont' work yet.

3) Yeah

Excellent questions. let me know if you run into any other issues

**Comment by sabinbajracharya** [comment]
@angle943 I have pushed changes addressing this issue in #44.
