### ISSUE TITLE
[Windows] Spacing between table column title should be equal

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#347]
![image](https://user-images.githubusercontent.com/59204822/94560597-837cdd80-0280-11eb-9559-d25074d9ebbc.png)

**Comment by mofodox** [comment]
@webdeveloperswj The issue persists when the window is on a small screen or the window size changed, the table column title shrinks @kristykjlee

**Comment by nsushman** [comment]
> @webdeveloperswj The issue persists when the window is on a small screen or the window size changed, the table column title shrinks @kristykjlee

Hey @mofodox , the image above highlights the issue in the navigation bar and not the table column title.
Check out this gif. It's at this point that the menu widths break (because the word wrapping gets triggered on the "Invalid Blocks")
![fQT3F86ZvU](https://user-images.githubusercontent.com/18399270/98456869-b7b0bb80-21a7-11eb-8d08-d34f5a98726f.gif)

**Comment by mofodox** [comment]
> > @webdeveloperswj The issue persists when the window is on a small screen or the window size changed, the table column title shrinks @kristykjlee
> 
> 
> 
> Hey @mofodox , the image above highlights the issue in the navigation bar and not the table column title.
> 
> Check out this gif. It's at this point that the menu widths break (because the word wrapping gets triggered on the "Invalid Blocks")
> 
> ![fQT3F86ZvU](https://user-images.githubusercontent.com/18399270/98456869-b7b0bb80-21a7-11eb-8d08-d34f5a98726f.gif)

@nsushman Yes that's what I'm referring to hehe

**Comment by nsushman** [comment]
@mofodox @kristykjlee this issue could be fixed as a bug by:

**Option 1**
collapsing the menu if the width goes below 1405px (or 1440px for standard resolution) instead of the current 1280px collapse.

1405px Breaks
![image](https://user-images.githubusercontent.com/18399270/98469857-1443c300-2208-11eb-81de-1d7e98704e3a.png)

1280px Collapses
![image](https://user-images.githubusercontent.com/18399270/98469918-5836c800-2208-11eb-8bc3-17837071d16e.png)


**Option 2**

The right behaviour should be developed in the controls, where the width of the label should be reduced once the text wraps.

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
