### ISSUE TITLE
[Windows] When right clicked on any text under Validators, Banks, My Accounts and My Friend gives option for copy link 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#360]
**Bug Description**
When right clicked on any text under Validators, Banks, My Accounts and My Friend gives option for copy link and when that link is pasted in browser it shows 404 error

**Steps to Reproduce**
1. Go to any one of "Validators, Banks, My Accounts and My Friend"
2. Right Click on Account names
3. Copy link and paste in chrome

**Expected behavior**
No link required

**Actual behavior**
When right clicked on any text under Validators, Banks, My Accounts and My Friend gives option for copy link and when that link is pasted in browser it shows 404 error

**Screenshots/Recordings**
https://recordit.co/UONrKa0BN5

**OS and Browser**
 - OS: [Windows 7]
 - Browser [Chromw]

**Additional context**
App Version Alpha 19

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by kcrnac** [comment]
What should actually happen in this case? 

- Copy Link option should not even be shown when someone right clicks on Validators, Banks, etc. ? Or
- Link should not be copied to clipboard?

**Comment by webdeveloperswj** [comment]
@kcrnac Copy Link option should not even be shown when someone right clicks on Validators, Banks, would be better

**Comment by brian316** [comment]
Can I be assigned to this?

**Comment by brian316** [comment]
I made my first pull request!
---
similar to @webdeveloperswj observation, but I also noticed you can copy the link for tabs
![context](https://user-images.githubusercontent.com/3878246/95927905-e7b99a00-0d74-11eb-89a3-2002ab8dea65.png)
[Previous behavior in prod](https://recordit.co/U4SwlLxFWI)

Keep in mind when you see the `Inspect Element` in the context menu it only shows up in development, not in production.
[Previous behavior in dev](https://recordit.co/Yh73YozXdp)
[Updated behavior ](https://recordit.co/OMmW8owzLA)

Conclusion:
I disabled the context menu, except for copying the QR code image because that seems useful. Inspect element still works in development.

**Comment by manishram** [comment]
@angle943 I download the TheNewBoston Application from:
https://github.com/thenewboston-developers/Account-Manager/releases/download/v1.0.0-alpha.28/TNB-Account-Manager-1.0.0-alpha.28-win.exe

And when I do right click on the account names I get "Inspect Element" instead of "Copy Link". As @brian316 said should have happened in the development version and not on the production version. So the "Download" button on the site points to the development version instead or production?

**Comment by FrostMegaByte** [comment]
I also wanted to let it be known that I got similar behaviour like @manishram after downloading the latest Windows version via https://thenewboston.com/download

The Account Manager application shows the "Inspect Element" option, from which I can likely conclude that currently the development version is being shared instead of the production version.
