### ISSUE TITLE
Strange Behavior of Point 

### ISSUE THREAD

**Issue by GitNegi** [thenewboston-developers/Account-Manager#438]
**Bug Description**
After adding 20 -> 999999xxx upto 20 ,21th 9 show  1 means now total transaction cost become 3.

![image](https://user-images.githubusercontent.com/66105456/98456458-e75dc480-21a3-11eb-9e16-b8088ee449ab.png)

**Account Number**
6807e8e6a8d31491f407325fd360b6c118e6b8058fdbea17dc15716746fd103b

**Comment by Hristijan95** [comment]
I think we can use something like [this](https://github.com/peterolson/BigInteger.js) to solve this issue. 
Or maybe it's better to add a limit on the amount of coins you can transfer - which I think would be a better solution.

**Comment by giacomo-b** [comment]
> 
> 
> I think we can use something like [this](https://github.com/peterolson/BigInteger.js) to solve this issue.
> Or maybe it's better to add a limit on the amount of coins you can transfer - which I think would be a better solution.

Pull request #458 fixes this. No need to use `BigInt` or another dependency since `Number.MAX_SAFE_INTEGER` is way higher than the max coin supply.

**Comment by brmendez** [comment]
@giacomo-b I was also looking into utilizing `yup` for form validation. I plugged this line into my local environment and it doesn't throw the intended message:
> Coins must be lower than 9,000,000,000,000,000

It's most likely due to the `callbackWithRef` (the `INVALID_AMOUNT_ERROR` arg?) taking precedence.

Another thing to note, I am not sure how the UX is meant to be handled when the user reaches the invalid amount (i.e. `9999999999999999`), I still see the `total` misrepresented — should the input prevent the user from entering additional characters?

**Comment by shivam2704** [comment]
just found out the max number of coins to supply is 281,474,976,710,656, that's 15 digits,
so why to reach 20 digits right now.
