### ISSUE TITLE
[Linux]Remove Arrow On TNB28 App version

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#479]
**Bug Description**
Removed small black Arrows its not usable there & not working in there

**Steps to Reproduce**
1. Launch TNB 28 app
2. Go to validators
3. Select any validator
4. Open Accounts Tab

**Expected behavior**
If Account number large then when user click on that arrow account number whole display or expand.

**Actual behavior**
Account number not so long so there its not usable for arrow 

**Screenshots/Recordings**
https://prnt.sc/vl7ja8

**OS and Browser**
 - OS:  Windows 10
 - Browser  Chrome

**Comment by Ramin-RX7** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/52785580/99697506-0b26e180-2aa5-11eb-9c32-105bcccc5d47.png)
As you can see I need to have that button because about 10 characters are not shown in one line in every column.
but if they can decrease 'Balance' column width, I will agree with you because it will be useless

**Comment by buckyroberts** [comment]
Moved to https://github.com/thenewboston-developers/Design/issues/27
