### ISSUE TITLE
[Windows]TNB ver_30 Login as a same account number but transaction shows different in different operating system

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#507]
**Bug Description**
Login as a same account number but transaction shows different in different operating system

**Steps to Reproduce**
1. Launch TNB 30 app on windows
2. Launch TNB 30 app on Linux
3. click on "My Accounts"(+) icon
4. select Add existing Account
5. Enter Signing Key
6. click on add button 
7. Now go to Linux machine
8. Repeat steps 3 to 6
9. select "my Accounts" in windows
10. go to "Transactions Tab"
11. select my accounts in Linux
12. go to "transaction"

**Expected behavior**
If Login as a same account number in different operating system Transaction Entry will be same showing

**Actual behavior**
If Login as a same account number in different operating system Transaction Entry not same showing

**Screenshots/Recordings**
https://prnt.sc/vo7aq8 -windows
https://prnt.sc/vo7cg4 -Linux

**OS and Browser**
 - OS: Windows 10,Linux
 - Browser Chrome

**Comment by Ramin-RX7** [comment]
I saw even dates and times of transactions are different (do your both Linux and windows have the same time zone? (is it even important?))
for example on 2020-11-16 in windows there is only one transaction but in Linux there are two (with different time).
(I asked about your time zone because in your screenshots there is 1.5/13.5 hours difference in their clock)

**Comment by angle943** [comment]
grouping these issue together #515
