### ISSUE TITLE
[Mac]Only Sender Side Transaction Recorded but Receiver end Transaction not Recorded

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Account-Manager#533]
**Bug Description**
Only Sender Side Transaction Recorded but Receiver end Transaction not Recorded

**Steps to Reproduce**
1. Launch TNB 31 on mac
2. Click on Send Coins Button
3. Select 'To' Account
4. Enter Coins
5. Click on Send Button
6. go to the sender Account Transaction Tab
7. go to the Receiver Account Transaction Tab

**Expected behavior**
Entry should be Recorded Both Side

**Actual behavior**
Receiver Account only receives notification but in Transaction Tab Not Any Record shown it
**Screenshots/Recordings**
https://prnt.sc/vypxqs

**OS and Browser**
 - OS: [ Mac , Windows 10]

**Comment by angle943** [comment]
@buckyroberts from what I understand about this issue, it appears that the problem is that the `transactions` table is not live updated..?

Send coins while you are in the transaction table, and it won't show it until you come back into the transaction table.

Should we add logic to make this live update whenever notification comes in?

**Comment by buckyroberts** [comment]
We can consider changing this if we begin hearing more feedback, otherwise we can keep it as it. Some might even prefer static data to ensure things are not constantly shifting around when trying to view transactions.
