### ISSUE TITLE
Change the Mac Installer Manager icon to a separate icon to distinguish it from the actual app

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Account-Manager#543]
************************
**PAYMENT PEOPLE: Please pay `stweyel` for the bug bounty!**
************************

**Bug Description**
The installer icon for the mac is very confusing, since it looks identical to our actual TNB app icon, it is hard to tell which one is the installer and which one is the app:

![Screen Shot 2021-01-17 at 1 36 30 PM](https://user-images.githubusercontent.com/5943963/104856806-63256d00-58c9-11eb-9f72-21837dccb897.png)

**Steps to Reproduce**
1. either download the TNB app from the website, or run `npm run build` with the Account Manager.
2. click on the `dmg` file to start the installation process.
3. you should see the red installer file on your desktop

** AC **
1. icon should be different (possible icon mock is required).
2. name of the file should also be different. Possibly something like "TNB Installer v.1.2.1"

**Account Number**
67077b2397f99fb6c63185af25cdf49d43736b22b7ea5dd68089a04cd4dbf8cf

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by angle943** [comment]
Here's an example of how Spotify handles it. They have a separate icon for the instsaller, and named the file `Install Spotify`

![Screen Shot 2021-01-18 at 10 36 30 AM](https://user-images.githubusercontent.com/5943963/104952319-19945b00-5979-11eb-9c5b-5d2cdb23addb.png)

**Comment by stweyel** [comment]
A suggestion for the disk image.
<img width="200" alt="tnb disk" src="https://user-images.githubusercontent.com/25363181/107941040-6aec3600-6f89-11eb-84ae-19f71d1cd91b.png">

Account Number
94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by angle943** [comment]
o I like that. Can the person managing this Give 1000 coins to @stweyel ? I listed as a `bug bounty`

**Comment by stweyel** [comment]
Oh great. Here's a zip containing various sizes and the icns file.
[TNB Disk Image.zip](https://github.com/thenewboston-developers/Account-Manager/files/5987966/TNB.Disk.Image.zip)

**Comment by bojan-ilijevski** [comment]
Do I have to be on Mac to resolve this issue?

**Comment by stweyel** [comment]
This icon is actually a common version of a disk image adaption. Which is the usual container for mac installer packages or files which have to be copied to the hd (as is thenewboston download).
I guess that icon group is not suitable for a windows installer exe, which is quite a different thing.
Windows icons also share a different format. While it's pretty easy to change icons on mac by cut & paste, you'll need some extra steps on windows to do that.
Since the win installer exe icon suffers from the same issue i'll provide an alternative icon for that purpose.

**Comment by sun-jay** [comment]
Could someone point me in the direction to access the .dmg source code in order to change the thumbnail image?

Account number
c0cbf80f3dbac1d93da883d7ac6d818ae7346e7994c2e623ff3e0576b88a19bd

**Comment by angle943** [comment]
I've upped the bounty to 5000 for this. Please read the documentation of `electron` to see where the file is supposed to be. If someone tells you where it is, then why wouldn't they just create the PR?

**Comment by stweyel** [comment]
Not sure how the dmg is created here. I never would care about any code solution for that task. Easiest is to go with a dmg creator like: https://sourceforge.net/projects/dmgcreator/
There're some others around.

**Comment by stweyel** [comment]
FYI: Checked out how it's done here but couldn't get it working. This is really weird. forge.config settings seem to have no effect on the icons. Tried several changes but without any luck so far. Only noticeable change happens if the buildResource path in electron-builder is changed. I'll investigate further on this and do a PR if i had success.

**Comment by stweyel** [comment]
got it working, will do a PR later

**Comment by angle943** [comment]
paid for both bounty and ticket
